ustl::memblock Class Reference
ustl::memblock Class Reference
Memory Management
Allocated memory block.
#include <ustl.h>
Public Member Functions
memblock (const void *p, size_type n)
memblock (size_type n)
memblock (const cmemlink &b)
memblock (const memlink &b)
memblock (const memblock &b)
virtual void unlink (void) noexcept
void assign (const cmemlink &l)
const memblock & operator= (const cmemlink &l)
const memblock & operator= (const memlink &l)
const memblock & operator= (const memblock &l)
void swap (memblock &l) noexcept
void assign (const void *p, size_type n)
Copies data from p, n.
void reserve (size_type newSize, bool bExact=false)
Reallocates internal block to hold at least newSize bytes.
void resize (size_type newSize, bool bExact=true)
resizes the block to newSize bytes, reallocating if necessary.
iterator insert (const_iterator start, size_type size)
Shifts the data in the linked block from start to start + n.
iterator erase (const_iterator start, size_type size)
Shifts the data in the linked block from start + n to start.
void clear (void) noexcept
size_type capacity (void) const
bool is_linked (void) const
size_type max_size (void) const
void manage (memlink &l)
void deallocate (void) noexcept
Frees internal data.
void shrink_to_fit (void)
Reduces capacity to match size.
void manage (void *p, size_type n) noexcept
void copy_link (void)
"Instantiate" a linked block by allocating and copying the linked data.
void read (istream &is)
Reads the object from stream s.
void read_file (const char *filename)
Reads the entire file "filename".
memblock (memblock &&b)
memblock & operator= (memblock &&b)
void swap (memblock &&l)
Public Member Functions inherited from ustl::memlink
memlink (void *p, size_type n)
memlink (const void *p, size_type n)
memlink (rcself_t l)
memlink (const cmemlink &l)
pointer data (void)
const_pointer data (void) const
iterator begin (void)
iterator iat (size_type i)
iterator end (void)
const_iterator begin (void) const
const_iterator end (void) const
const_iterator iat (size_type i) const
size_type writable_size (void) const
rcself_t operator= (const cmemlink &l)
rcself_t operator= (rcself_t l)
void link (const void *p, size_type n)
void link (void *p, size_type n)
void link (const cmemlink &l)
void link (memlink &l)
void link (const void *first, const void *last)
void link (void *first, void *last)
void relink (const void *p, size_type n)
void relink (void *p, size_type n)
void swap (memlink &l)
void fill (const_iterator start, const void *p, size_type elsize, size_type elCount=1) noexcept
void insert (const_iterator start, size_type size)
void erase (const_iterator start, size_type size)
void read (istream &is)
Reads the object from stream s.
Public Member Functions inherited from ustl::cmemlink
cmemlink (const void *p, size_type n)
cmemlink (const cmemlink &l)
void link (const void *p, size_type n)
Attaches the object to pointer p of size n.
void link (const cmemlink &l)
void link (const void *first, const void *last)
void relink (const void *p, size_type n)
A fast alternative to link which can be used when relinking to the same block (i.e. when it is resized)
rcself_t operator= (const cmemlink &l)
bool operator== (const cmemlink &l) const noexcept
Compares to memory block pointed by l. Size is compared first.
void swap (cmemlink &l)
size_type size (void) const
size_type max_size (void) const
size_type readable_size (void) const
bool empty (void) const
const_pointer data (void) const
const_pointer cdata (void) const
iterator begin (void) const
iterator iat (size_type i) const
iterator end (void) const
void resize (size_type n)
void read (istream &)
void write (ostream &os) const
Writes the object to stream os.
size_type stream_size (void) const noexcept
Returns the number of bytes required to write this object to a stream.
void text_write (ostringstream &os) const
Writes the object to stream os.
void write_file (const char *filename, int mode=0644) const
Writes the data to file "filename".
Protected Member Functions
virtual size_type minimumFreeCapacity (void) const noexcept __attribute__((const))
Additional Inherited Members
Public Types inherited from ustl::memlink
typedef value_type * pointer
typedef cmemlink::pointer const_pointer
typedef cmemlink::const_iterator const_iterator
typedef pointer iterator
typedef const memlink & rcself_t
Public Types inherited from ustl::cmemlink
typedef char value_type
typedef const value_type * pointer
typedef const value_type * const_pointer
typedef value_type reference
typedef value_type const_reference
typedef size_t size_type
typedef uint32_t written_size_type
typedef ptrdiff_t difference_type
typedef const_pointer const_iterator
typedef const_iterator iterator
typedef const cmemlink & rcself_t
Detailed Description
Allocated memory block.
Adds memory management capabilities to memlink. Uses malloc and realloc to maintain the internal pointer, but only if allocated using members of this class, or if linked to using the Manage() member function. Managed memory is automatically freed in the destructor.
Member Function Documentation
void ustl::memblock::manage (void * p, size_type n) noexcept
Assumes control of the memory block p of size n. The block assigned using this function will be freed in the destructor.
void ustl::memblock::reserve (size_type newSize, bool bExact = false)
Reallocates internal block to hold at least newSize bytes.
Additional memory may be allocated, but for efficiency it is a very good idea to call reserve before doing byte-by-byte edit operations. The block size as returned by size() is not altered. reserve will not reduce allocated memory. If you think you are wasting space, call deallocate and start over. To avoid wasting space, use the block for only one purpose, and try to get that purpose to use similar amounts of memory on each iteration.
References ustl::copy_n(), ustl::min(), and ustl::NextPow2().
Referenced by erase(), ustl::ostringstream::overflow(), read_file(), and resize().
The documentation for this class was generated from the following files:
memblock.h
memblock.cc