Swap Algorithms
Swap Algorithms
Mutating Algorithms
Functions
template<typename ForwardIterator1 , typename ForwardIterator2 >
ForwardIterator2 ustl::swap_ranges (ForwardIterator1 first, ForwardIterator2 last, ForwardIterator2 result)
template<typename Assignable >
void ustl::swap (Assignable &a, Assignable &b)
template<typename Iterator >
void ustl::iter_swap (Iterator a, Iterator b)
Detailed Description
Algorithms for swapping elements.
Function Documentation
template<typename Iterator > void ustl::iter_swap (Iterator a, Iterator b) inline
Equivalent to swap (*a, *b)
References ustl::swap().
Referenced by ustl::next_permutation(), ustl::pop_heap(), ustl::prev_permutation(), ustl::random_shuffle(), ustl::reverse(), ustl::rotate(), ustl::rotate_fast(), and ustl::swap_ranges().
template<typename Assignable > void ustl::swap (Assignable & a, Assignable & b) inline
Assigns the contents of a to b and the contents of b to a. This is used as a primitive operation by many other algorithms.
Referenced by ustl::iter_swap(), ustl::ostream::swap(), ustl::istream::swap(), and ustl::transpose().
template<typename ForwardIterator1 , typename ForwardIterator2 > ForwardIterator2 ustl::swap_ranges (ForwardIterator1 first, ForwardIterator2 last, ForwardIterator2 result) inline
Swaps corresponding elements of [first, last) and [result,)
References ustl::iter_swap().